namespace DarkSoulsSeriesComboRandomizer
{
    public static class MapNameExtensions
    {
        public static string ToFriendlyName(this MapName name) => name switch
        {
            // ---- Dark Souls Remastered --------------------------------------
            MapName.DS1StartingCell => "DS1 Starting Cell",
            MapName.Depths => "Depths",
            MapName.SewerChamber => "Sewer Chamber",
            MapName.UndeadBurgUndeadParish => "Undead Burg / Undead Parish",
            MapName.UndeadBurgResidence => "Undead Burg Residence",
            MapName.LowerUndeadBurg => "Lower Undead Burg",
            MapName.LowerUndeadBurgResidence => "Lower Undead Burg Residence",
            MapName.FirelinkShrine => "Firelink Shrine",
            MapName.PaintedWorld => "Painted World",
            MapName.PaintedWorldAnnex => "Painted World Annex",
            MapName.DarkrootGarden => "Darkroot Garden",
            MapName.Oolacile => "Oolacile",
            MapName.OolacileAfterGough => "Oolacile After Gough",
            MapName.Catacombs => "Catacombs",
            MapName.TombOfTheGiants => "Tomb of the Giants",
            MapName.TombOfTheGiantsPostLordvessel => "Tomb of the Giants Post Lordvessel",
            MapName.GreatHollowAshLake => "Great Hollow / Ash Lake",
            MapName.Blighttown => "Blighttown",
            MapName.DemonRuinsLostIzalith => "Demon Ruins / Lost Izalith",
            MapName.DemonRuinsLostIzalithPostLordvessel => "Demon Ruins / Lost Izalith Post Lordvessel",
            MapName.SensFortress => "Sen's Fortress",
            MapName.SensCage => "Sen's Cage",
            MapName.AnorLondo => "Anor Londo",
            MapName.NewLondoRuinsValleyOfDrakes => "New Londo Ruins / Valley of Drakes",
            MapName.NewLondoRuinsPostSeal => "New Londo Ruins Post Seal",
            MapName.ValleyOfDrakes => "Valley of Drakes",
            MapName.FourKings => "Four Kings",
            MapName.DukesArchives => "Duke's Archives",
            MapName.TowerCell => "Tower Cell",
            MapName.ArchivesTower => "Archives Tower",
            MapName.ArchivesTowerExtra => "Archives Tower Extra",
            MapName.ArchivesTowerGiantCell => "Archives Tower Giant Cell",
            MapName.CrystalCave => "Crystal Cave",
            MapName.FirelinkAltar => "Firelink Altar",
            MapName.FirstLordSoul => "First Lord Soul",
            MapName.SecondLordSoul => "Second Lord Soul",
            MapName.ThirdLordSoul => "Third Lord Soul",
            MapName.KilnOfTheFirstFlame => "Kiln of the First Flame",
            MapName.NorthernUndeadAsylum => "Northern Undead Asylum",
            MapName.NorthernUndeadAsylumF2East => "Northern Undead Asylum F2 East",
            MapName.NorthernUndeadAsylumF2West => "Northern Undead Asylum F2 West",
            MapName.NorthernUndeadAsylumExit => "Northern Undead Asylum Exit",

            // ---- Dark Souls II: Scholar of the First Sin --------------------
            MapName.ThingsBetwixt => "Things Betwixt",
            MapName.ThingsBetwixtPostStatue => "Things Betwixt Post Statue",
            MapName.Majula => "Majula",
            MapName.MajulaHouse => "Majula House",
            MapName.LenigrastsHouse => "Lenigrast's House",
            MapName.DragonTalonRoom => "Dragon Talon Room",
            MapName.ForestOfFallenGiants => "Forest of Fallen Giants",
            MapName.ForestOfFallenGiantsPostSoldierKey => "Forest of Fallen Giants Post Soldier Key",
            MapName.ForestOfFallenGiantsIronKeyRoom => "Forest of Fallen Giants Iron Key Room",
            MapName.BrightstoneCoveTseldora => "Brightstone Cove Tseldora",
            MapName.BrightStoneKeyRoom => "Brightstone Key Room",
            MapName.TseldoraDen => "Tseldora Den",
            MapName.AldiasKeep => "Aldia's Keep",
            MapName.AldiaSideRoom => "Aldia Side Room",
            MapName.TheLostBastilleBelfryLuna => "The Lost Bastille & Belfry Luna",
            MapName.BastilleCells => "Bastille Cells",
            MapName.StraidsCell => "Straid's Cell",
            MapName.RuinSentinelBuilding => "Ruin Sentinel Building",
            MapName.HarvestValleyEarthenPeak => "Harvest Valley & Earthen Peak",
            MapName.NomansWharf => "No-man's Wharf",
            MapName.IronKeepBelfrySol => "Iron Keep & Belfry Sol",
            MapName.HuntsmansCopseUndeadPurgatory => "Huntsman's Copse & Undead Purgatory",
            MapName.UndeadLockaway => "Undead Lockaway",
            MapName.TheGutterBlackGulch => "The Gutter & Black Gulch",
            MapName.HiddenChamber => "Hidden Chamber",
            MapName.HavelArmorRoom => "Havel Armor Room",
            MapName.DragonAerieDragonShrine => "Dragon Aerie & Dragon Shrine",
            MapName.MajulaShadedWoods => "Majula <-> Shaded Woods",
            MapName.HeidesTowerNomansWharf => "Heide's Tower <-> No-man's Wharf",
            MapName.FloodedPassageSideRoom => "Flooded Passage Side Room",
            MapName.HeidesTowerOfFlame => "Heide's Tower of Flame",
            MapName.ShadedWoodsShrineOfWinter => "Shaded Woods & Shrine of Winter",
            MapName.VengarlsBodyRoom => "Vengarl's Body Room",
            MapName.ChestAfterVengarl => "Chest after Vengarl",
            MapName.LionMageSetChest => "Lion Mage Set Chest",
            MapName.FangKeyLion => "Fang Key Lion",
            MapName.DoorsOfPharros => "Doors of Pharros",
            MapName.GraveOfSaints => "Grave of Saints",
            MapName.MemoryOfVammarOrroAndJeigh => "Memory of Vammar, Orro, and Jeigh",
            MapName.ShrineOfAmana => "Shrine of Amana",
            MapName.RiseOfTheDead => "Rise of the Dead",
            MapName.DrangleicCastleThroneOfWant => "Drangleic Castle & Throne of Want",
            MapName.Nashandra => "Nashandra",
            MapName.LookingGlassKnightArena => "Looking Glass Knight Arena",
            MapName.UndeadCrypt => "Undead Crypt",
            MapName.DragonMemories => "Dragon Memories",
            MapName.DarkChasmOfOld => "Dark Chasm of Old",
            MapName.ShulvaSanctumCity => "Shulva, Sanctum City",
            MapName.PriestessChamber => "Priestess' Chamber",
            MapName.DragonSanctum => "Dragon Sanctum",
            MapName.BrumeTower => "Brume Tower",
            MapName.BrumeTowerWithOnlyTowerKey => "Brume Tower With Only Tower Key",
            MapName.BrumeTowerWithOnlyScorchingIronScepter => "Brume Tower With Only Scorching Iron Scepter",
            MapName.BrumeTowerWithBothKeys => "Brume Tower With Both Keys",
            MapName.FrozenEleumLoyce => "Frozen Eleum Loyce",
            MapName.FrozenEleumLoyceAfterAava => "Frozen Eleum Loyce After Aava",
            MapName.ReinderValley => "Reindeer Valley",
            MapName.MemoryOfTheKing => "Memory of the King",

            // ---- Dark Souls III ---------------------------------------------
            MapName.HighWallOfLothricGarden => "High Wall of Lothric / Garden",
            MapName.OceirosGarden => "Oceiros' Garden",
            MapName.DarkwraithCell => "Darkwraith Cell",
            MapName.LothricCastle => "Lothric Castle",
            MapName.UndeadSettlement => "Undead Settlement",
            MapName.VelkaShrine => "Velka Shrine",
            MapName.ArchdragonPeak => "Archdragon Peak",
            MapName.RoadOfSacrificesFarronKeep => "Road of Sacrifices / Farron Keep",
            MapName.GrandArchives => "Grand Archives",
            MapName.CathedralOfTheDeep => "Cathedral of the Deep",
            MapName.IrithyllAnorLondo => "Irithyll / Anor Londo",
            MapName.CatacombsCarthusSmoulderingLake => "Catacombs Carthus / Smouldering Lake",
            MapName.DungeonProfanedCapital => "Dungeon / Profaned Capital",
            MapName.LedgeOutsideJailbreakersWindow => "Ledge Outside Jailbreaker's Window",
            MapName.JailCells => "Jail Cells",
            MapName.OldCell => "Old Cell",
            MapName.CemetaryFirelinkUntendedGraves => "Cemetery / Firelink / Untended Graves",
            MapName.UntendedGraves => "Untended Graves",
            MapName.FirelinkTower => "Firelink Tower",
            MapName.FirelinkRoof => "Firelink Roof",
            MapName.FirstCinders => "First Cinders",
            MapName.SecondCinders => "Second Cinders",
            MapName.ThirdCinders => "Third Cinders",
            MapName.KilnOfFlameFlamelessShrine => "Kiln of Flame / Flameless Shrine",
            MapName.PaintedWorldOfAriandel => "Painted World of Ariandel",
            MapName.PaintedWorldSecondHalf => "Painted World Second Half",
            MapName.DregHeap => "Dreg Heap",
            MapName.RingedCity => "Ringed City",
            MapName.FilianoresRest => "Filianore's Rest",

            _ => throw new ArgumentOutOfRangeException(nameof(name), name, "Unknown MapName")
        };
    }
}