<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.SharpDX" Version="3.1.2" />
    <PackageReference Include="Pfim" Version="0.11.4" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SoulsFormats">
      <HintPath>..\..\..\SoulsFormatsNEXT\SoulsFormats\bin\Debug\net6.0\SoulsFormats.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
